insert into cars (id, type, model, year) values (1, 'Mazda', 'Protege', 1997);
insert into cars (id, type, model, year) values (2, 'Acura', 'MDX', 2002);
insert into cars (id, type, model, year) values (3, 'Dodge', 'Neon', 1996);
insert into cars (id, type, model, year) values (4, 'Dodge', 'Stratus', 2002);
insert into cars (id, type, model, year) values (5, 'Mercury', 'Tracer', 1991);
insert into cars (id, type, model, year) values (6, 'BMW', '525', 2005);
insert into cars (id, type, model, year) values (7, 'Chevrolet', 'Uplander', 2008);
insert into cars (id, type, model, year) values (8, 'Mercury', 'Tracer', 1988);
insert into cars (id, type, model, year) values (9, 'Geo', 'Prizm', 1996);
insert into cars (id, type, model, year) values (10, 'Chrysler', 'Pacifica', 2005);
insert into cars (id, type, model, year) values (11, 'Ford', 'Aerostar', 1996);
insert into cars (id, type, model, year) values (12, 'Toyota', 'Camry Solara', 2008);
insert into cars (id, type, model, year) values (13, 'MG', 'MGB', 1977);
insert into cars (id, type, model, year) values (14, 'Jeep', 'Grand Cherokee', 1996);
insert into cars (id, type, model, year) values (15, 'Saturn', 'S-Series', 1994);
insert into cars (id, type, model, year) values (16, 'Suzuki', 'X-90', 1996);
insert into cars (id, type, model, year) values (17, 'Isuzu', 'Hombre', 1997);
insert into cars (id, type, model, year) values (18, 'Nissan', 'Sentra', 2006);
insert into cars (id, type, model, year) values (19, 'Dodge', 'Ram', 2011);
insert into cars (id, type, model, year) values (20, 'Chevrolet', 'Lumina', 2000);
insert into cars (id, type, model, year) values (21, 'Ford', 'Festiva', 1992);
insert into cars (id, type, model, year) values (22, 'Mazda', 'Protege', 1993);
insert into cars (id, type, model, year) values (23, 'Lincoln', 'Town Car', 2006);
insert into cars (id, type, model, year) values (24, 'Mercury', 'Sable', 1999);
insert into cars (id, type, model, year) values (25, 'Subaru', 'Impreza', 2004);
insert into cars (id, type, model, year) values (26, 'Ford', 'Escort', 1996);
insert into cars (id, type, model, year) values (27, 'Chevrolet', 'Silverado 1500', 2008);
insert into cars (id, type, model, year) values (28, 'Saturn', 'Outlook', 2007);
insert into cars (id, type, model, year) values (29, 'BMW', 'M5', 1992);
insert into cars (id, type, model, year) values (30, 'Toyota', 'Paseo', 1992);
insert into cars (id, type, model, year) values (31, 'Honda', 'Accord', 1995);
insert into cars (id, type, model, year) values (32, 'Ford', 'Mustang', 1972);
insert into cars (id, type, model, year) values (33, 'Acura', 'Legend', 1993);
insert into cars (id, type, model, year) values (34, 'Volkswagen', 'Scirocco', 1984);
insert into cars (id, type, model, year) values (35, 'Saab', '9-5', 2005);
insert into cars (id, type, model, year) values (36, 'Ford', 'Taurus', 2001);
insert into cars (id, type, model, year) values (37, 'Chevrolet', 'Express 3500', 2007);
insert into cars (id, type, model, year) values (38, 'Pontiac', '6000', 1988);
insert into cars (id, type, model, year) values (39, 'Jaguar', 'XJ Series', 1992);
insert into cars (id, type, model, year) values (40, 'Buick', 'Reatta', 1990);
insert into cars (id, type, model, year) values (41, 'Acura', 'RSX', 2006);
insert into cars (id, type, model, year) values (42, 'Toyota', 'Camry', 2005);
insert into cars (id, type, model, year) values (43, 'Dodge', 'Ram', 2009);
insert into cars (id, type, model, year) values (44, 'Oldsmobile', 'Bravada', 2000);
insert into cars (id, type, model, year) values (45, 'Volkswagen', 'Golf', 2002);
insert into cars (id, type, model, year) values (46, 'Lexus', 'LS', 2005);
insert into cars (id, type, model, year) values (47, 'Ford', 'F250', 2006);
insert into cars (id, type, model, year) values (48, 'Maybach', '57', 2005);
insert into cars (id, type, model, year) values (49, 'Pontiac', 'Sunbird', 1994);
insert into cars (id, type, model, year) values (50, 'Plymouth', 'Neon', 1995);
insert into cars (id, type, model, year) values (51, 'Cadillac', 'Seville', 1998);
insert into cars (id, type, model, year) values (52, 'Chevrolet', 'Caprice Classic', 1993);
insert into cars (id, type, model, year) values (53, 'Buick', 'Rendezvous', 2003);
insert into cars (id, type, model, year) values (54, 'Volkswagen', 'Jetta', 1988);
insert into cars (id, type, model, year) values (55, 'Toyota', 'Sequoia', 2004);
insert into cars (id, type, model, year) values (56, 'Porsche', 'Panamera', 2012);
insert into cars (id, type, model, year) values (57, 'GMC', '2500', 1993);
insert into cars (id, type, model, year) values (58, 'Cadillac', 'CTS', 2006);
insert into cars (id, type, model, year) values (59, 'Chevrolet', 'Corvette', 1999);
insert into cars (id, type, model, year) values (60, 'BMW', '760', 2006);
insert into cars (id, type, model, year) values (61, 'Mitsubishi', 'Pajero', 2001);
insert into cars (id, type, model, year) values (62, 'Mitsubishi', 'GTO', 1991);
insert into cars (id, type, model, year) values (63, 'Chevrolet', '2500', 1999);
insert into cars (id, type, model, year) values (64, 'Jaguar', 'X-Type', 2004);
insert into cars (id, type, model, year) values (65, 'Ford', 'Tempo', 1994);
insert into cars (id, type, model, year) values (66, 'Lincoln', 'LS', 2001);
insert into cars (id, type, model, year) values (67, 'GMC', 'Canyon', 2006);
insert into cars (id, type, model, year) values (68, 'Cadillac', 'Eldorado', 1998);
insert into cars (id, type, model, year) values (69, 'Honda', 'Insight', 2006);
insert into cars (id, type, model, year) values (70, 'Ford', 'Ranger', 1993);
insert into cars (id, type, model, year) values (71, 'Ford', 'Tempo', 1990);
insert into cars (id, type, model, year) values (72, 'Mazda', 'B-Series Plus', 1994);
insert into cars (id, type, model, year) values (73, 'Chrysler', '300', 2010);
insert into cars (id, type, model, year) values (74, 'Pontiac', 'Grand Prix', 2006);
insert into cars (id, type, model, year) values (75, 'Chevrolet', 'Camaro', 1979);
insert into cars (id, type, model, year) values (76, 'Jaguar', 'X-Type', 2008);
insert into cars (id, type, model, year) values (77, 'Honda', 'Civic', 2010);
insert into cars (id, type, model, year) values (78, 'Suzuki', 'SX4', 2009);
insert into cars (id, type, model, year) values (79, 'Ford', 'F350', 2003);
insert into cars (id, type, model, year) values (80, 'Nissan', 'Altima', 1994);
insert into cars (id, type, model, year) values (81, 'GMC', 'Canyon', 2008);
insert into cars (id, type, model, year) values (82, 'Lexus', 'ES', 2003);
insert into cars (id, type, model, year) values (83, 'GMC', 'Acadia', 2011);
insert into cars (id, type, model, year) values (84, 'Dodge', 'Ram 1500', 2007);
insert into cars (id, type, model, year) values (85, 'Audi', '100', 1994);
insert into cars (id, type, model, year) values (86, 'Audi', 'TT', 2009);
insert into cars (id, type, model, year) values (87, 'GMC', 'Suburban 1500', 1995);
insert into cars (id, type, model, year) values (88, 'Jaguar', 'XK Series', 1998);
insert into cars (id, type, model, year) values (89, 'Ford', 'Mustang', 1969);
insert into cars (id, type, model, year) values (90, 'Chevrolet', 'Silverado 3500', 2009);
insert into cars (id, type, model, year) values (91, 'Audi', '5000CS Quattro', 1986);
insert into cars (id, type, model, year) values (92, 'Mercury', 'Cougar', 1988);
insert into cars (id, type, model, year) values (93, 'Pontiac', '6000', 1987);
insert into cars (id, type, model, year) values (94, 'Ford', 'E-Series', 2010);
insert into cars (id, type, model, year) values (95, 'Ford', 'Thunderbird', 1958);
insert into cars (id, type, model, year) values (96, 'Mercury', 'Grand Marquis', 1995);
insert into cars (id, type, model, year) values (97, 'Ford', 'Explorer Sport Trac', 2000);
insert into cars (id, type, model, year) values (98, 'Mercury', 'Sable', 1987);
insert into cars (id, type, model, year) values (99, 'Dodge', 'Nitro', 2010);
insert into cars (id, type, model, year) values (100, 'Cadillac', 'Escalade EXT', 2005);
