insert into car (id, owner_id, make, model, year) values (1, 37, 'Mazda', 'Protege', 1997);
insert into car (id, owner_id, make, model, year) values (2, 32, 'Acura', 'MDX', 2002);
insert into car (id, owner_id, make, model, year) values (3, 4, 'Dodge', 'Neon', 1996);
insert into car (id, owner_id, make, model, year) values (4, 18, 'Dodge', 'Stratus', 2002);
insert into car (id, owner_id, make, model, year) values (5, 7, 'Mercury', 'Tracer', 1991);
insert into car (id, owner_id, make, model, year) values (6, 21, 'BMW', '525', 2005);
insert into car (id, owner_id, make, model, year) values (7, 8, 'Chevrolet', 'Uplander', 2008);
insert into car (id, owner_id, make, model, year) values (8, 22, 'Mercury', 'Tracer', 1988);
insert into car (id, owner_id, make, model, year) values (9, 13, 'Geo', 'Prizm', 1996);
insert into car (id, owner_id, make, model, year) values (10, 26, 'Chrysler', 'Pacifica', 2005);
insert into car (id, owner_id, make, model, year) values (11, 17, 'Ford', 'Aerostar', 1996);
insert into car (id, owner_id, make, model, year) values (12, 13, 'Toyota', 'Camry Solara', 2008);
insert into car (id, owner_id, make, model, year) values (13, 14, 'MG', 'MGB', 1977);
insert into car (id, owner_id, make, model, year) values (14, 31, 'Jeep', 'Grand Cherokee', 1996);
insert into car (id, owner_id, make, model, year) values (15, 26, 'Saturn', 'S-Series', 1994);
insert into car (id, owner_id, make, model, year) values (16, 4, 'Suzuki', 'X-90', 1996);
insert into car (id, owner_id, make, model, year) values (17, 34, 'Isuzu', 'Hombre', 1997);
insert into car (id, owner_id, make, model, year) values (18, 3, 'Nissan', 'Sentra', 2006);
insert into car (id, owner_id, make, model, year) values (19, 23, 'Dodge', 'Ram', 2011);
insert into car (id, owner_id, make, model, year) values (20, 14, 'Chevrolet', 'Lumina', 2000);
insert into car (id, owner_id, make, model, year) values (21, 25, 'Ford', 'Festiva', 1992);
insert into car (id, owner_id, make, model, year) values (22, 31, 'Mazda', 'Protege', 1993);
insert into car (id, owner_id, make, model, year) values (23, 11, 'Lincoln', 'Town Car', 2006);
insert into car (id, owner_id, make, model, year) values (24, 33, 'Mercury', 'Sable', 1999);
insert into car (id, owner_id, make, model, year) values (25, 24, 'Subaru', 'Impreza', 2004);
insert into car (id, owner_id, make, model, year) values (26, 27, 'Ford', 'Escort', 1996);
insert into car (id, owner_id, make, model, year) values (27, 19, 'Chevrolet', 'Silverado 1500', 2008);
insert into car (id, owner_id, make, model, year) values (28, 9, 'Saturn', 'Outlook', 2007);
insert into car (id, owner_id, make, model, year) values (29, 17, 'BMW', 'M5', 1992);
insert into car (id, owner_id, make, model, year) values (30, 15, 'Toyota', 'Paseo', 1992);
insert into car (id, owner_id, make, model, year) values (31, 11, 'Honda', 'Accord', 1995);
insert into car (id, owner_id, make, model, year) values (32, 4, 'Ford', 'Mustang', 1972);
insert into car (id, owner_id, make, model, year) values (33, 36, 'Acura', 'Legend', 1993);
insert into car (id, owner_id, make, model, year) values (34, 34, 'Volkswagen', 'Scirocco', 1984);
insert into car (id, owner_id, make, model, year) values (35, 35, 'Saab', '9-5', 2005);
insert into car (id, owner_id, make, model, year) values (36, 23, 'Ford', 'Taurus', 2001);
insert into car (id, owner_id, make, model, year) values (37, 31, 'Chevrolet', 'Express 3500', 2007);
insert into car (id, owner_id, make, model, year) values (38, 8, 'Pontiac', '6000', 1988);
insert into car (id, owner_id, make, model, year) values (39, 22, 'Jaguar', 'XJ Series', 1992);
insert into car (id, owner_id, make, model, year) values (40, 16, 'Buick', 'Reatta', 1990);
insert into car (id, owner_id, make, model, year) values (41, 19, 'Acura', 'RSX', 2006);
insert into car (id, owner_id, make, model, year) values (42, 10, 'Toyota', 'Camry', 2005);
insert into car (id, owner_id, make, model, year) values (43, 29, 'Dodge', 'Ram', 2009);
insert into car (id, owner_id, make, model, year) values (44, 7, 'Oldsmobile', 'Bravada', 2000);
insert into car (id, owner_id, make, model, year) values (45, 31, 'Volkswagen', 'Golf', 2002);
insert into car (id, owner_id, make, model, year) values (46, 15, 'Lexus', 'LS', 2005);
insert into car (id, owner_id, make, model, year) values (47, 17, 'Ford', 'F250', 2006);
insert into car (id, owner_id, make, model, year) values (48, 26, 'Maybach', '57', 2005);
insert into car (id, owner_id, make, model, year) values (49, 25, 'Pontiac', 'Sunbird', 1994);
insert into car (id, owner_id, make, model, year) values (50, 35, 'Plymouth', 'Neon', 1995);
insert into car (id, owner_id, make, model, year) values (51, 12, 'Cadillac', 'Seville', 1998);
insert into car (id, owner_id, make, model, year) values (52, 19, 'Chevrolet', 'Caprice Classic', 1993);
insert into car (id, owner_id, make, model, year) values (53, 28, 'Buick', 'Rendezvous', 2003);
insert into car (id, owner_id, make, model, year) values (54, 2, 'Volkswagen', 'Jetta', 1988);
insert into car (id, owner_id, make, model, year) values (55, 9, 'Toyota', 'Sequoia', 2004);
insert into car (id, owner_id, make, model, year) values (56, 12, 'Porsche', 'Panamera', 2012);
insert into car (id, owner_id, make, model, year) values (57, 27, 'GMC', '2500', 1993);
insert into car (id, owner_id, make, model, year) values (58, 30, 'Cadillac', 'CTS', 2006);
insert into car (id, owner_id, make, model, year) values (59, 20, 'Chevrolet', 'Corvette', 1999);
insert into car (id, owner_id, make, model, year) values (60, 15, 'BMW', '760', 2006);
insert into car (id, owner_id, make, model, year) values (61, 9, 'Mitsubishi', 'Pajero', 2001);
insert into car (id, owner_id, make, model, year) values (62, 6, 'Mitsubishi', 'GTO', 1991);
insert into car (id, owner_id, make, model, year) values (63, 8, 'Chevrolet', '2500', 1999);
insert into car (id, owner_id, make, model, year) values (64, 14, 'Jaguar', 'X-Type', 2004);
insert into car (id, owner_id, make, model, year) values (65, 25, 'Ford', 'Tempo', 1994);
insert into car (id, owner_id, make, model, year) values (66, 9, 'Lincoln', 'LS', 2001);
insert into car (id, owner_id, make, model, year) values (67, 7, 'GMC', 'Canyon', 2006);
insert into car (id, owner_id, make, model, year) values (68, 19, 'Cadillac', 'Eldorado', 1998);
insert into car (id, owner_id, make, model, year) values (69, 5, 'Honda', 'Insight', 2006);
insert into car (id, owner_id, make, model, year) values (70, 17, 'Ford', 'Ranger', 1993);
insert into car (id, owner_id, make, model, year) values (71, 19, 'Ford', 'Tempo', 1990);
insert into car (id, owner_id, make, model, year) values (72, 26, 'Mazda', 'B-Series Plus', 1994);
insert into car (id, owner_id, make, model, year) values (73, 20, 'Chrysler', '300', 2010);
insert into car (id, owner_id, make, model, year) values (74, 11, 'Pontiac', 'Grand Prix', 2006);
insert into car (id, owner_id, make, model, year) values (75, 22, 'Chevrolet', 'Camaro', 1979);
insert into car (id, owner_id, make, model, year) values (76, 27, 'Jaguar', 'X-Type', 2008);
insert into car (id, owner_id, make, model, year) values (77, 38, 'Honda', 'Civic', 2010);
insert into car (id, owner_id, make, model, year) values (78, 34, 'Suzuki', 'SX4', 2009);
insert into car (id, owner_id, make, model, year) values (79, 11, 'Ford', 'F350', 2003);
insert into car (id, owner_id, make, model, year) values (80, 13, 'Nissan', 'Altima', 1994);
insert into car (id, owner_id, make, model, year) values (81, 21, 'GMC', 'Canyon', 2008);
insert into car (id, owner_id, make, model, year) values (82, 29, 'Lexus', 'ES', 2003);
insert into car (id, owner_id, make, model, year) values (83, 31, 'GMC', 'Acadia', 2011);
insert into car (id, owner_id, make, model, year) values (84, 1, 'Dodge', 'Ram 1500', 2007);
insert into car (id, owner_id, make, model, year) values (85, 36, 'Audi', '100', 1994);
insert into car (id, owner_id, make, model, year) values (86, 18, 'Audi', 'TT', 2009);
insert into car (id, owner_id, make, model, year) values (87, 29, 'GMC', 'Suburban 1500', 1995);
insert into car (id, owner_id, make, model, year) values (88, 14, 'Jaguar', 'XK Series', 1998);
insert into car (id, owner_id, make, model, year) values (89, 36, 'Ford', 'Mustang', 1969);
insert into car (id, owner_id, make, model, year) values (90, 36, 'Chevrolet', 'Silverado 3500', 2009);
insert into car (id, owner_id, make, model, year) values (91, 33, 'Audi', '5000CS Quattro', 1986);
insert into car (id, owner_id, make, model, year) values (92, 30, 'Mercury', 'Cougar', 1988);
insert into car (id, owner_id, make, model, year) values (93, 25, 'Pontiac', '6000', 1987);
insert into car (id, owner_id, make, model, year) values (94, 19, 'Ford', 'E-Series', 2010);
insert into car (id, owner_id, make, model, year) values (95, 13, 'Ford', 'Thunderbird', 1958);
insert into car (id, owner_id, make, model, year) values (96, 37, 'Mercury', 'Grand Marquis', 1995);
insert into car (id, owner_id, make, model, year) values (97, 10, 'Ford', 'Explorer Sport Trac', 2000);
insert into car (id, owner_id, make, model, year) values (98, 32, 'Mercury', 'Sable', 1987);
insert into car (id, owner_id, make, model, year) values (99, 12, 'Dodge', 'Nitro', 2010);
insert into car (id, owner_id, make, model, year) values (100, 33, 'Cadillac', 'Escalade EXT', 2005);
